### ISSUE TITLE
.fsx files are not found when using FSI from Visual Studio, add hint on using #I command

### ISSUE THREAD

**Issue by nicenemo** [mbraceproject/MBrace.StarterKit#58] opened 2015-10-12 21:29 UTC
When trying the handson tutorial from fsi within Visual Studio 2015 you get messages about
not being able to find thespiancluster.fsx in the cwd. Trying to change the cwd as found on Stackoverflow does not work for this problem. 

Using something like #I @"c:\users\hans\source\repos\mbrace\mbrace.starterkit\handsontutorial" does work. A hint to use the above or something better saves F# novices like me 20 minutes.

**Comment by eiriktsarpalis** [comment] 2015-10-12 22:28
I can't reproduce this. Did you try building the solution before running the scripts?

**Comment by nicenemo** [comment] 2015-10-12 22:33
yes I did a build all. and using fsi from within vs 2015. cwd is set to something like appdata\temp can try again tomorrow with complete log/screenshots if that helps.

**Comment by eiriktsarpalis** [comment] 2015-10-12 22:42
The cwd shouldn't factor in here. Relative paths in #r and #I directives are resolved w.r.t. the source file directory.

**Comment by dsyme** [comment] 2015-10-14 10:11
@nicenemo If you can send us repro steps that would be great.

**Comment by nicenemo** [comment] 2015-10-15 12:35
I Installed F# as documented for use without Visual Studio.
 I planned to try Visual Studio Code.
Could not get it working easily for something simple as a command line tool.
Planning to look into that later. Installed Visual Studio Community 2015 with all options instead.
I downloaded the repo using git command line to my local machine.
opened the solution. Build it. It builds fine.
copied the #load command to F# interactive --> error without the mentioned search path addition
![capture](https://cloud.githubusercontent.com/assets/2677108/10513712/b8867282-7349-11e5-958f-eeadbbcff243.PNG)

any further steps I can to do to clarify? uninstall everything, start from scratch and record everyting?

**Comment by eiriktsarpalis** [comment] 2015-10-15 12:49
Instead of copying and pasting code to the REPL, try highlighting it from the editor and then hit Alt+Enter.

**Comment by nicenemo** [comment] 2015-10-17 12:18
Ευχαριστώ πολύ!, that works indeed.
![image](https://cloud.githubusercontent.com/assets/2677108/10558711/f9e985c0-74d9-11e5-8beb-c2a035871ad9.png)

**Comment by eiriktsarpalis** [comment] 2015-10-17 12:24
No problem! Closing this then :)

**Closed by eiriktsarpalis** 2015-10-17 12:24 UTC
