### ISSUE TITLE
Update link on http://m-brace.net

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.StarterKit#7] opened 2015-03-31 11:53 UTC
I presume this is now the canonical location for the starter kit.

The link to the samples in the all-important "getting started instructions" on http://m-brace.net still refers to the elastacloud ZIP and should probably now point here.

Given the versioning situation for mbrace, we have to (very carefully) update the link in the getting-started material so that people get exactly the right set of samples for the version of MBrace they are using on their cluster.  This may be different for people installing their cloud service from scratch and those using Brisk, depending on the version that Brisk installs.

(Having the separate versioned releases for the starter kit is definitely useful! That's great to see.)

**Comment by isaacabraham** [comment] 2015-03-31 11:56
Yes. On the Brisk side we need to update our links and probably close down the old repo, although we might keep it open for Elastacloud / Brisk specific demos in the future though.

The latest version of MBrace does have a form of version checking so this should mitigate some of the risks regarding connecting with an old cluster to a newer version on the client side.

Once MBrace hits 1.x - or perhaps sooner - we'll start to offer multiple versions of MBrace through Brisk during the provisioning process. At this point it's probably premature to offer that though.

**Comment by dsyme** [comment] 2015-03-31 12:00
I don't think it's totally premature - I feel MBrace-on-Azure is already at "1.0 alpha" or "1.0 preview" - it really depends how much work it is for you.  

At least, I'd appreciate it if you changed the text on the drop-down box where currently only "MBrace" is shown to at least say "MBrace 0.6.4" so I know which version is being installed.

**Comment by dsyme** [comment] 2015-03-31 12:03
BTW I'll submit a change to this repo to rename "azure/Demos" to "azure/HandsOnTutorial".

**Comment by isaacabraham** [comment] 2015-03-31 12:11
It's give and take - currently we just store the *latest* versions of "MBrace on Brisk" cloud services and associated code in our repositories, so we can push the latest MBrace versions without a drop of code to the main Brisk code base in the background (as I have just done in the last ten minutes to upgrade to 0.6.5 alpha :)). The problem is that we only have a single version available and it's unclear which one it is.

If we start maintaining stricter versioning then new releases of MBrace will have to be associated with an associated release of Brisk (at least in the current implementation of Brisk - perhaps in the future we could change this behaviour).

**Comment by eiriktsarpalis** [comment] 2015-03-31 12:28
I just updated the links on the website.

**Comment by isaacabraham** [comment] 2015-03-31 12:30
I've also just updated our uservoice links to point to the correct repo.

I'll a little stretched for time today but both of you are admins of the elastacloud repo, feel free to remove the code samples and add a redirect readme if you like.

**Comment by eiriktsarpalis** [comment] 2015-03-31 15:01
Ok, looks like I can close this?

**Closed** 2015-03-31 15:42 UTC
